### ISSUE TITLE
Здравствуйте, вот такая ошибка:

### ISSUE THREAD

**Issue by gabochko** [JanchEwgen/MQTT-SberGate#16]
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
20241005-115559.313479: Start MQTT SberGate IoT Agent for Home Assistant version: 1.0.15
20241005-115559.313553: Запущено в системе: posix
20241005-115559.313690: Версия Python     : 3.12.6 (main, Sep 11 2024, 08:48:26) [GCC 13.2.1 20240309]
20241005-115559.313793: Размещение скрипта: /app/sber-gate.py
20241005-115559.313839: Текущая директория: /data
20241005-115559.313887: Размер Log файла  : 5270
20241005-115559.313927: Log Level         : info
20241005-115559.313966: Кодировка         : utf-8
20241005-115559.314037: Список файлов     : ['SberGate.log', 'devices.json', 'options.json']
20241005-115559.314084: Чтение базы устройств
20241005-115559.314274: Подключаемся к HA, (ha-api_url: http://192.168.1.11:8123)
20241005-115559.342114: Запрос устройств из Home Assistant выполнен штатно.
Traceback (most recent call last):
  File "/app/sber-gate.py", line 696, in <module>
    mqttc.connect(Options['sber-mqtt_broker'], Options['sber-mqtt_broker_port'], 60)
  File "/app/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/app/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 841, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -5] Name has no usable address
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
20241005-115911.023638: Start MQTT SberGate IoT Agent for Home Assistant version: 1.0.15
20241005-115911.023713: Запущено в системе: posix
20241005-115911.023760: Версия Python     : 3.12.6 (main, Sep 11 2024, 08:48:26) [GCC 13.2.1 20240309]
20241005-115911.023839: Размещение скрипта: /app/sber-gate.py
20241005-115911.023886: Текущая директория: /data
20241005-115911.023933: Размер Log файла  : 6232
20241005-115911.024020: Log Level         : info
20241005-115911.024067: Кодировка         : utf-8
20241005-115911.024140: Список файлов     : ['SberGate.log', 'devices.json', 'options.json']
20241005-115911.024190: Чтение базы устройств
20241005-115911.024410: Подключаемся к HA, (ha-api_url: http://192.168.1.11:8123)
20241005-115911.057625: Запрос устройств из Home Assistant выполнен штатно.
Traceback (most recent call last):
  File "/app/sber-gate.py", line 696, in <module>
    mqttc.connect(Options['sber-mqtt_broker'], Options['sber-mqtt_broker_port'], 60)
  File "/app/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/app/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 841, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -5] Name has no usable address
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

Делал все по инструкции, перепроверял, 1-й раз запустился(даже в салюте отобразилось, но управлять не получилось отображается как контроллер), потом отключил его(аддон), попытался включить снова, а она не запускается

**Comment by gabochko** [comment]
![Uploading Безымянный.png…]()

**Comment by gabochko** [comment]
![Безымянный](https://github.com/user-attachments/assets/f85a84e5-f062-4e02-9da9-424f524176cd)

**Comment by gabochko** [comment]
Помогите пожалуйста

**Comment by JanchEwgen** [comment]
#

> ocket.gaierror: [Errno -5] Name has no usable address

Вероятно по какой-то причине не может получить адрес сберовского хоста (mqtt-partners.iot.sberdevices.ru). Возможно это временный глюк был. Сейчас перезапустил у себя, всё работает штатно. Интернет в HA точно нормально работает?

**Comment by gabochko** [comment]
Здравствуйте еще раз, сейчас такая ошибка

**Comment by gabochko** [comment]
А не, все раюотает

**Comment by gabochko** [comment]
Полгода не получалось, спасибо вам огромное, все работает, куда можно сделать пожертвование?

**Comment by digitizer77** [comment]
А у меня вот весь день такая ошибка. Дополнение несколько раз пытается запустится и в результате не запускается.

20250331-182200.747238: Запрос устройств из Home Assistant выполнен штатно.
    mqttc.connect(Options['sber-mqtt_broker'], Options['sber-mqtt_broker_port'], 60)
  File "/app/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/app/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 841, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 978, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name does not resolve
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

Вчера все работало.

**Comment by JanchEwgen** [comment]
> [Errno -2] Name does not resolve

По ошибке вероятно примерно то же что и выше. Приложение не может получить IP адрес по переданным параметрам. Проверить настройки, пропинговать mqtt-partners.iot.sberdevices.ru, желательно с сервера HA. Возможно поможет универсальное средство: семь бед - один ресет... Возможно на сервере HA что-то с сетью случилось...

**Comment by digitizer77** [comment]
Вы правы. Похоже это у меня что-то накрылось в HA. Выдало проблему с Systemd-Resolved. Буду у себя разбираться.
